import { App, ItemView, Notice, Plugin, PluginSettingTab, Setting, TFile, WorkspaceLeaf } from "obsidian";
import { OllamaClient } from "./src/ollama";
import { OllovinSettings, RetrievalResult, AIActionPlan, ChangePreview } from "./src/types";
import { VaultIndex } from "./src/vault-index";
import { Retriever } from "./src/retrieval";
import { ActionPlanner, SYSTEM_PROMPT } from "./src/agent";
import { generateTestVault } from "./src/test-vault-generator";

const DEFAULT_SETTINGS: OllovinSettings = { ollamaEndpoint: "http://localhost:11434", llmModel: "", embeddingModel: "", indexVersion: 1 };
export const VIEW_TYPE_OLLOVIN = "ollovin-sidebar";

export default class OllovinPlugin extends Plugin {
  settings!: OllovinSettings; ollama!: OllamaClient; index!: VaultIndex; retriever!: Retriever; planner!: ActionPlanner;
  private undoLast: (() => Promise<void>) | null = null;
  async onload() {
    await this.loadSettings(); this.ollama = new OllamaClient(this.settings.ollamaEndpoint); this.index = new VaultIndex(this.app, this.settings, this.ollama); await this.index.load();
    this.retriever = new Retriever(this.ollama, () => this.settings.embeddingModel, () => this.index.getChunks()); this.planner = new ActionPlanner(this.app);
    this.registerView(VIEW_TYPE_OLLOVIN, leaf => new OllovinView(leaf, this)); this.addRibbonIcon("brain", "Открыть Ollovin", () => void this.activateView());
    const commands: [string,string,()=>void][] = [["open", "Открыть помощника", () => void this.activateView()], ["analyze", "Анализировать текущую заметку", () => void this.analyzeCurrentNote()], ["related", "Найти связанные заметки", () => void this.findRelated()], ["suggest", "Предложить изменения", () => void this.suggestChanges()], ["undo", "Отменить последнее изменение", () => void this.undo()], ["reindex", "Переиндексировать хранилище", () => void this.reindex()], ["test-vault", "Создать тестовые заметки", () => void this.generateTestVault()]];
    for (const [id, name, callback] of commands) this.addCommand({ id, name: `Ollovin: ${name}`, callback }); this.addSettingTab(new OllovinSettingTab(this.app, this));
  }
  async loadSettings() { this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData()); }
  async saveSettings() { await this.saveData(this.settings); this.ollama = new OllamaClient(this.settings.ollamaEndpoint); this.retriever = new Retriever(this.ollama, () => this.settings.embeddingModel, () => this.index.getChunks()); }
  getCurrentFile(): TFile | null { return this.app.workspace.getActiveFile(); }
  async activateView() { const leaves = this.app.workspace.getLeavesOfType(VIEW_TYPE_OLLOVIN); if (leaves.length) return void await this.app.workspace.revealLeaf(leaves[0]); const leaf = this.app.workspace.getRightLeaf(false) ?? this.app.workspace.getLeaf(true); await leaf.setViewState({ type: VIEW_TYPE_OLLOVIN, active: true }); await this.app.workspace.revealLeaf(leaf); }
  getView(): OllovinView | null { const v = this.app.workspace.getLeavesOfType(VIEW_TYPE_OLLOVIN)[0]?.view; return v instanceof OllovinView ? v : null; }
  async reindex() { const n = new Notice("Ollovin: индексация хранилища…", 0); try { await this.index.rebuild((c,t) => n.setMessage(`Ollovin: индексация ${c}/${t}`)); n.hide(); new Notice(`Ollovin: проиндексировано фрагментов — ${this.index.size}`); this.refreshViews(); } catch(e) { n.hide(); new Notice(`Ollovin: ошибка индексации — ${err(e)}`); } }
  async analyzeCurrentNote() { const f=this.getCurrentFile(); if(!f)return void new Notice("Ollovin: сначала откройте Markdown-заметку"); await this.activateView(); await this.getView()?.analyzeFile(f); }
  async findRelated() { const f=this.getCurrentFile(); if(!f)return void new Notice("Ollovin: сначала откройте Markdown-заметку"); await this.activateView(); await this.getView()?.findRelatedForFile(f); }
  async suggestChanges() { const f=this.getCurrentFile(); if(!f)return void new Notice("Ollovin: сначала откройте Markdown-заметку"); await this.activateView(); await this.getView()?.suggestChangesForFile(f); }
  setUndo(fn:()=>Promise<void>) { this.undoLast=fn; }
  async undo() { if(!this.undoLast)return void new Notice("Ollovin: нет изменений для отмены"); try { await this.undoLast(); this.undoLast=null; new Notice("Ollovin: последнее изменение отменено"); this.refreshViews(); } catch(e) { new Notice(`Ollovin: ошибка отмены — ${err(e)}`); } }
  async generateTestVault() { try { await generateTestVault(this.app); new Notice("Ollovin: тестовые заметки созданы"); } catch(e) { new Notice(`Ollovin: ошибка создания тестовых заметок — ${err(e)}`); } }
  refreshViews() { for(const l of this.app.workspace.getLeavesOfType(VIEW_TYPE_OLLOVIN)) if(l.view instanceof OllovinView) l.view.render(); }
}

class OllovinView extends ItemView {
  constructor(leaf:WorkspaceLeaf, private readonly plugin:OllovinPlugin){super(leaf)}
  getViewType(){return VIEW_TYPE_OLLOVIN} getDisplayText(){return "Ollovin"} getIcon(){return "brain"}
  async onOpen(){this.render()} async onClose(){this.contentEl.empty()}
  render(){ this.contentEl.empty(); this.contentEl.addClass("ollovin-view"); this.contentEl.createEl("h2",{text:"🧠 Ollovin"}); this.contentEl.createDiv({cls:"ollovin-status",text:`Индекс: ${this.plugin.index.size} фрагментов`});
    const input=this.contentEl.createEl("textarea",{attr:{placeholder:"Задайте вопрос по вашему хранилищу…"}}); this.button("Спросить Ollovin",()=>void this.ask(input.value)); this.button("Анализировать текущую заметку",()=>void this.analyzeCurrent()); this.button("Найти связанные заметки",()=>void this.findCurrentRelated()); this.button("Предложить изменения",()=>void this.suggestCurrentChanges()); this.button("Отменить последнее изменение",()=>void this.plugin.undo()); this.button("Создать тестовые заметки",()=>void this.plugin.generateTestVault()); this.button("Переиндексировать хранилище",()=>void this.plugin.reindex()); this.contentEl.createEl("h3",{text:"Результат"}); this.contentEl.createDiv({cls:"ollovin-response"}); }
  private button(text:string,cb:()=>void){const b=this.contentEl.createEl("button",{text});b.addEventListener("click",cb)} private response(){return this.contentEl.querySelector(".ollovin-response") as HTMLElement} private current(){return this.plugin.getCurrentFile()}
  async ask(q:string){if(!q.trim())return void new Notice("Ollovin: введите вопрос");const r=this.response();r.setText("Поиск по хранилищу…");try{const results=await this.plugin.retriever.search(q);const p=`Вопрос пользователя:\n${q}\n\nКонтекст хранилища:\n${context(results)}\n\nОтвечай только на основании контекста. Если данных недостаточно, скажи об этом.`;r.setText(await this.plugin.ollama.generate(this.plugin.settings.llmModel,p,SYSTEM_PROMPT))}catch(e){r.setText(`Ошибка: ${err(e)}`);new Notice(`Ollovin: ${err(e)}`)}}
  async analyzeCurrent(){const f=this.current();if(!f)return void new Notice("Ollovin: сначала откройте Markdown-заметку");await this.analyzeFile(f)}
  async analyzeFile(f:TFile){const r=this.response();r.setText("Анализ заметки…");try{const c=await this.plugin.app.vault.cachedRead(f);const x=await this.plugin.retriever.search(c.slice(0,2000));const p=`Проанализируй текущую заметку. Верни резюме, основные темы, предлагаемые теги и wikilinks. Ничего не изменяй.\n\nЗаметка:\n${c}\n\nСвязанный контекст:\n${context(x.filter(v=>v.chunk.path!==f.path))}`;r.setText(await this.plugin.ollama.generate(this.plugin.settings.llmModel,p,SYSTEM_PROMPT))}catch(e){r.setText(`Ошибка анализа: ${err(e)}`);new Notice(`Ollovin: ${err(e)}`)}}
  async findCurrentRelated(){const f=this.current();if(!f)return void new Notice("Ollovin: сначала откройте Markdown-заметку");await this.findRelatedForFile(f)}
  async findRelatedForFile(f:TFile){const r=this.response();r.setText("Поиск связанных заметок…");try{const c=await this.plugin.app.vault.cachedRead(f);const items=(await this.plugin.retriever.search(c.slice(0,1600),10)).filter(v=>v.chunk.path!==f.path);r.empty();r.createEl("strong",{text:"Связанные заметки"});if(!items.length)r.createDiv({text:"Связанных заметок не найдено. Попробуйте переиндексировать хранилище."});for(const x of items){const row=r.createDiv({text:`${x.chunk.title} — ${(x.score*100).toFixed(0)}%`});row.addClass("ollovin-related-row");row.addEventListener("click",()=>void this.plugin.app.workspace.openLinkText(x.chunk.path,f.path))}}catch(e){r.setText(`Ошибка поиска: ${err(e)}`);new Notice(`Ollovin: ${err(e)}`)}}
  async suggestCurrentChanges(){const f=this.current();if(!f)return void new Notice("Ollovin: сначала откройте Markdown-заметку");await this.suggestChangesForFile(f)}
  async suggestChangesForFile(f:TFile){const r=this.response();r.setText("Подготовка предложений…");try{const c=await this.plugin.app.vault.cachedRead(f);const x=await this.plugin.retriever.search(c.slice(0,1800),10);const p=`Предложи полезные безопасные изменения для текущей заметки. Можно добавлять/удалять теги и wikilinks, редактировать текст или frontmatter. Не удаляй заметки. Верни ТОЛЬКО JSON.\n\nТекущая заметка: ${f.path}\n${c}\n\nКонтекст:\n${context(x.filter(v=>v.chunk.path!==f.path))}`;const raw=await this.plugin.ollama.generate(this.plugin.settings.llmModel,p,SYSTEM_PROMPT);const plan=this.plugin.planner.buildPlan(raw);const previews=await this.plugin.planner.preview(plan);this.renderPlan(r,plan,previews)}catch(e){r.setText(`Ошибка формирования предложений: ${err(e)}`);new Notice(`Ollovin: ${err(e)}`)}}
  private renderPlan(r:HTMLElement,plan:AIActionPlan,previews:ChangePreview[]){r.empty();r.createEl("h4",{text:"Предлагаемые изменения"});r.createDiv({text:plan.summary||"Ollovin предлагает следующие изменения:"});const checks:HTMLInputElement[]=[];previews.forEach(p=>{const row=r.createDiv({cls:"ollovin-plan-row"});const cb=row.createEl("input",{type:"checkbox"});cb.checked=p.valid;checks.push(cb);row.createSpan({text:` ${describe(p)}${p.error?` — ${p.error}`:""}`});if(p.before!==undefined&&p.after!==undefined){const d=row.createEl("pre");d.setText(diff(p.before,p.after))}});const b=r.createEl("button",{text:"Применить выбранные"});b.addEventListener("click",()=>void this.applySelected(r,previews,checks))}
  private async applySelected(r:HTMLElement,p:ChangePreview[],checks:HTMLInputElement[]){const selected=p.filter((_,i)=>checks[i].checked);if(!selected.length)return void new Notice("Ollovin: выберите хотя бы одно изменение");try{const undo=await this.plugin.planner.apply(selected);this.plugin.setUndo(undo);r.empty();r.createDiv({text:"✓ Изменения применены"});const b=r.createEl("button",{text:"Отменить"});b.addEventListener("click",()=>void this.plugin.undo());new Notice("Ollovin: изменения применены")}catch(e){new Notice(`Ollovin: изменения не применены — ${err(e)}`)}}
}
function describe(p:ChangePreview){const a=p.action;switch(a.type){case"ADD_TAG":return`Добавить тег ${a.tag} в ${a.file}`;case"REMOVE_TAG":return`Удалить тег ${a.tag} из ${a.file}`;case"ADD_LINK":return`Добавить ссылку [[${a.target}]] в ${a.file}`;case"REMOVE_LINK":return`Удалить ссылку [[${a.target}]] из ${a.file}`;case"EDIT_NOTE":return`Изменить текст ${a.file}`;case"CREATE_NOTE":return`Создать заметку ${a.file}`;case"MOVE_NOTE":return`Переместить ${a.file} → ${a.destination}`;case"RENAME_NOTE":return`Переименовать ${a.file} → ${a.newPath}`;case"UPDATE_FRONTMATTER":return`Обновить свойства ${a.file}`}}
function diff(a:string,b:string){const x=a.split("\n"),y=b.split("\n"),o:string[]=[];for(const l of x)if(!y.includes(l))o.push(`- ${l}`);for(const l of y)if(!x.includes(l))o.push(`+ ${l}`);return o.slice(0,80).join("\n")||"Изменения форматирования/структуры"}function context(r:RetrievalResult[]){return r.map((x,i)=>`[#${i+1}] ${x.chunk.path}\n${x.chunk.content}`).join("\n\n")}function err(e:unknown){return e instanceof Error?e.message:String(e)}

class OllovinSettingTab extends PluginSettingTab{constructor(app:App,private readonly plugin:OllovinPlugin){super(app,plugin)}display(){const{containerEl}=this;containerEl.empty();containerEl.createEl("h2",{text:"Ollovin — локальный ИИ для Obsidian"});new Setting(containerEl).setName("Адрес Ollama").setDesc("Адрес локального сервера Ollama.").addText(t=>t.setValue(this.plugin.settings.ollamaEndpoint).onChange(async v=>{this.plugin.settings.ollamaEndpoint=v.trim();await this.plugin.saveSettings()}));new Setting(containerEl).setName("Модель ИИ").setDesc("Модель для чата и анализа.").addText(t=>t.setValue(this.plugin.settings.llmModel).setPlaceholder("qwen3:8b").onChange(async v=>{this.plugin.settings.llmModel=v.trim();await this.plugin.saveSettings()}));new Setting(containerEl).setName("Модель эмбеддингов").setDesc("Модель для семантического поиска.").addText(t=>t.setValue(this.plugin.settings.embeddingModel).setPlaceholder("embeddinggemma").onChange(async v=>{this.plugin.settings.embeddingModel=v.trim();await this.plugin.saveSettings()}));new Setting(containerEl).setName("Подключение").setDesc("Проверить Ollama.").addButton(b=>b.setButtonText("Проверить Ollama").onClick(async()=>{try{const m=await this.plugin.ollama.testConnection();new Notice(`Ollama подключена — моделей: ${m.length}`)}catch(e){new Notice(`Ошибка подключения — ${err(e)}`)}}));new Setting(containerEl).setName("Тестовые данные").setDesc("Создать синтетическое хранилище.").addButton(b=>b.setButtonText("Создать тестовые заметки").onClick(()=>void this.plugin.generateTestVault()));new Setting(containerEl).setName("Индекс").setDesc(`Проиндексировано: ${this.plugin.index.size} фрагментов.`).addButton(b=>b.setButtonText("Переиндексировать").onClick(()=>void this.plugin.reindex()))}}
